# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9b2318643e3724a0a781340980ba2d038af9129e7107512304629bb452d90e2be79e204e2c93d611f3bb169159e9cc281919eca1fa64155ab98dc8d042d6a3a3

test:
  secret_key_base: d7a21d4dd6538ed4fdfff2060fa1eb950d9bd1aade90504fa39fd193bbe55fc63b5d6ebfba5d3479f368b72a2f54bbe0dc41272989356f3f0247d6a09010fafc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
